In [1]:
import pandas as pd
import numpy as np

In [2]:
# read the iris data into a DataFrame
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
col_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
iris = pd.read_csv(url, header=None, names=col_names)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
# apply the ceiling function to the numeric columns
iris.loc[:, 'sepal_length':'petal_width'] = iris.loc[:, 'sepal_length':'petal_width'].apply(np.ceil)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           6.0          4.0           2.0          1.0  Iris-setosa
1           5.0          3.0           2.0          1.0  Iris-setosa
2           5.0          4.0           2.0          1.0  Iris-setosa
3           5.0          4.0           2.0          1.0  Iris-setosa
4           5.0          4.0           2.0          1.0  Iris-setosa

In [4]:
# show all observations with features: 7, 3, 5, 2
iris[(iris.sepal_length==7) & (iris.sepal_width==3) & (iris.petal_length==5) & (iris.petal_width==2)]

     sepal_length  sepal_width  petal_length  petal_width          species
54            7.0          3.0           5.0          2.0  Iris-versicolor
58            7.0          3.0           5.0          2.0  Iris-versicolor
63            7.0          3.0           5.0          2.0  Iris-versicolor
68            7.0          3.0           5.0          2.0  Iris-versicolor
72            7.0          3.0           5.0          2.0  Iris-versicolor
73            7.0          3.0           5.0          2.0  Iris-versicolor
74            7.0          3.0           5.0          2.0  Iris-versicolor
75            7.0          3.0           5.0          2.0  Iris-versicolor
76            7.0          3.0           5.0          2.0  Iris-versicolor
77            7.0          3.0           5.0          2.0  Iris-versicolor
87            7.0          3.0           5.0          2.0  Iris-versicolor
91            7.0          3.0           5.0          2.0  Iris-versicolor
97            7.0          3.0           5.0          2.0  Iris-versicolor
123           7.0          3.0           5.0          2.0   Iris-virginica
126           7.0          3.0           5.0          2.0   Iris-virginica
127           7.0          3.0           5.0          2.0   Iris-virginica
146           7.0          3.0           5.0          2.0   Iris-virginica

In [5]:
# count the species for these observations
iris[(iris.sepal_length==7) & (iris.sepal_width==3) & (iris.petal_length==5) & (iris.petal_width==2)].species.value_counts()

Iris-versicolor    13
Iris-virginica      4
Name: species, dtype: int64

In [6]:
# count the species for all observations
iris.species.value_counts()

Iris-virginica     50
Iris-versicolor    50
Iris-setosa        50
Name: species, dtype: int64